/**
 * Historical thesis material. These sources are copied byte-for-byte from the
 * canonical Planning JSON files; they are not generated by the explorer.
 */
import experiment4Source from './sources/experiment-4-results.json' with { type: 'json' };
import experimentSummarySource from './sources/experiment-summary.json' with { type: 'json' };
import projectionSource from './sources/projection-data.json' with { type: 'json' };

export type CanonicalJsonValue = string | number | boolean | null | CanonicalJsonObject | readonly CanonicalJsonValue[];

export interface CanonicalJsonObject {
  readonly [key: string]: CanonicalJsonValue;
}

export interface FixedExperimentalProjectionRow {
  readonly years_invested: number;
  readonly cumulative_contributions_cad: number;
  readonly total_account_balance_cad: number;
}

export interface FixedExperimentalProjectionSource {
  readonly source: CanonicalJsonObject;
  readonly scenario: CanonicalJsonObject;
  readonly data: readonly FixedExperimentalProjectionRow[];
  readonly reproduction_note: CanonicalJsonObject;
}

/** Exact historical recreation values; do not regenerate with a formula. */
export const fixedExperimentalProjection = projectionSource as FixedExperimentalProjectionSource;

/** Raw canonical study summary, retained as source material without derived claims. */
export const experimentSummary = experimentSummarySource as unknown as CanonicalJsonObject;

/** Raw canonical Experiment 4 results, including its statistical-language warning. */
export const experiment4Results = experiment4Source as CanonicalJsonObject;

export const fixedExperimentalProjectionRows: readonly FixedExperimentalProjectionRow[] =
  fixedExperimentalProjection.data;
